### ISSUE TITLE
Upserting same document with the same _id creates a new document

### ISSUE THREAD

**Issue by hpaknia** [martin-helmich/php-mongomock#11]
I noticed upserting documents with the same `_id` does not update the first one. In general upserting documents with the same compound index should not create new documents.
I'm OK with opening a PR. Please advice.

**Comment by martin-helmich** [comment]
Whoops, that's not intended behaviour. Good catch. :+1:

PRs are always welcome. However, currently the `MockCollection` does not have any notion of indices (let alone unique indices) and on top of that, the update logic in particular is in dire need of refactoring. So fixing this might take some effort. If you like, you're welcome to have a go at it; I'll give pointers whereever I can. :slightly_smiling_face: 

Alternatively, you could open a pull request that contains one or a few failing test cases, and I'll pick it up from there as soon as I find the time.

**Comment by kevinkl3** [comment]
@martin-helmich 
I believe this was resolved on PR #12 . If that's the case this issue can be closed.
