### ISSUE TITLE
Create a new tag.

### ISSUE THREAD

**Issue by ruslanbaidan** [martin-helmich/php-mongomock#25]
Could you please create a new tag with the countDocuments method.

**Comment by martin-helmich** [comment]
Done! Thanks for the reminder.

**Comment by ruslanbaidan** [comment]
Thank you!

**Comment by ruslanbaidan** [comment]
Unfortunately we can't use the new tag as far as it requires "phpunit/phpunit": ">=8.0,<9.0".

**Comment by martin-helmich** [comment]
Ouch. Must have missed that. Will fix this shortly. Am 27.02.2019 12:48 schrieb ruslanbaydan <notifications@github.com>:Unfortunately we can't use the new tag as far as it requires "phpunit/phpunit": ">=8.0,<9.0".

**Comment by ruslanbaidan** [comment]
It would be nice if you could require ">=6,<9.0".
Thank you!

**Comment by martin-helmich** [comment]
:+1: Done
