### ISSUE TITLE
Constraint operator '$all' not yet implemented in MockCollection.

### ISSUE THREAD

**Issue by ruslanbaidan** [martin-helmich/php-mongomock#30]
When I try to use MockCollection to test query with "$all" operator, I get the following error:
"Constraint operator '$all' not yet implemented in MockCollection."
Could you tell if there are some plans to support the operator?

**Comment by martin-helmich** [comment]
No immediate plans. The time I’ve been able to invest in maintaining this repo has been scarce recently. Pull requests are welcome, though.
